-- Create db statement
CREATE DATABASE game
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

COMMENT ON DATABASE game
    IS 'Game data base';

-- Create db Schema
CREATE SCHEMA game
    AUTHORIZATION postgres;

-- Create USER table
CREATE TABLE game.USER (
  ID SERIAL PRIMARY KEY,
  USER_NAME VARCHAR(20) UNIQUE NOT NULL,
  PASSWORD VARCHAR(35) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO game.USER (USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES ("admin", "4db9152001819052dd64e1f8dbec251e", "Borislav", "Boydev");
COMMIT;

-- Create SCORE table
CREATE TABLE game.SCORE (
  USER_ID INTEGER NOT NULL,
  SCORE INTEGER NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES game.USER(id)
);

INSERT INTO game.SCORE (USER_ID, SCORE) VALUES (1, 3000);
COMMIT;